preons:

  baseline: 1.2rem;

  gutter: 2.5rem;

  # Base rules
  rules:  
    color:
      black: "#282828"
      blue: "#365e86"
      white: "#ffffff"
      grey: "#f1f5f1"
      grey-dark: "#89969d"
      transparent: "transparent"
      red: "#ff206b"
      mustard: "#e0b700"

    shadow:
      -large: "5px 11px 24px 2px rgba(0, 0, 0, 0.23)"

    border-style:
      solid: solid
      dotted: dotted
      dashed: dashed

    list-style:
      circle: circle
      disc: disc
      square: square
      decimal: decimal
      none: none
      decimal-leading-zero: decimal-leading-zero

    display: 
      b: block
      i: inline
      ib: inline-block
      t: table
      f: flex
      if: inline-flex
      n: none


    font-family: 
      heebo: "#{heebo sans-serif}"


    overflow: 
      scroll: scroll
      hidden: hidden
      auto: auto


    position: 
      relative: relative
      absolute: absolute
      fixed: fixed


    scaled: 
      n1: -1rem
      n2: -2rem
      n3: -3rem
      n4: -4rem
      n5: -5rem
      n6: -6rem
      n7: -7rem
      n8: -8rem
      n9: -9rem
      n10: -10rem
      0: 0
      1: 1rem
      2: 2rem
      3: 3rem
      4: 4rem
      5: 5rem
      6: 6rem
      7: 7rem
      8: 8rem
      9: 9rem
      10: 10rem

    negative-scaled: 
      n1: -1rem
      n2: -2rem
      n3: -3rem
      n4: -4rem
      n5: -5rem
      n6: -6rem
      n7: -7rem
      n8: -8rem
      n9: -9rem
      n10: -10rem

    scaledsmall: 
      0: 0
      1: 0.5rem
      2: 1rem
      3: 1.5rem
      4: 2rem
      5: 2.5rem
      6: 3rem

    # For fonts especially
    baselined: 
      -small: 2rem
      1: $baseline * 2
      2: $baseline * 2.5
      3: $baseline * 3
      -large: 4rem
      4: $baseline * 4
      5: $baseline * 5
      6: $baseline * 6
      7: $baseline * 6.5
      8: $baseline * 7.5

    decimal: 
      0: 0
      -10: .1
      -20: .2
      -30: .3
      -40: .4
      -50: .5
      -60: .6
      -70: .7
      -80: .8
      -90: .9
      -100: 1

    percentaged: 
      -5 : 5%
      -10: 10%
      -15: 15%
      -20: 20%
      -25: 25%
      -30: 30%
      -35: 35%
      -40: 40%
      -45: 45%
      -50: 50%
      -55: 55%
      -60: 60%
      -65: 65%
      -70: 70%
      -75: 75%
      -80: 80%
      -85: 85%
      -90: 90%
      -95: 95%
      -100: 100%
      -third: "(100% / 3)"
      -two-thirds: "(100% / 3 * 2)"
      -1-12: "(100% / 12)"
      -2-12: "(100% / 12)"
      -3-12: "(100% / 12)"

    special-sizes: 
      x: none
      -au: auto

    limited-percentage:
      -50: 50%

    tiny: 
      0: 0
      1: 1px
      2: 2px
      3: 3px
      4: 4px
      5: 5px

    discrete: 
      -wire : 1px
      -thin : 3px
      -xxsmall : 5px
      -xsmall : 1rem
      -small : 1.6rem
      -icon : 3.2rem
      -medium : 7rem
      -big : 10rem
      -xbig : 16rem
      -xxbig : 22rem
      -xxxbig : 32rem
      -super : 42rem
      -xsuper : 52rem
      -xxsuper : 62rem
      -xxxsuper : 72rem

    numbers: 
      1: 1
      2: 2
      3: 3
      4: 4
      5: 5

    text: 
      u: uppercase
      c: capitalize


    alignment: 
      -center: center
      -right: right
      -left: left


    weight: 
      b: 700


    decoration: 
      x: none
      u: underline


    letter-spacing: 
      1: 1px
      2: 2px
      3: 3px
      4: 4px

    font-size: 
      1: 1.3rem
      2: 1.6rem
      3: 2.0rem
      4: 2.4rem
      5: 2.7rem
      6: 3.2rem
      7: 3.8rem
      8: 4.8rem
      9: 6.4rem
      10: 7.6rem

    image-fill:
      fill: fill
      cover: cover
      contain: contain
      none: none
      
  # Preon breakpoints
  breakpoints:
    m: "only screen and (min-width: 768px)"
    l: "only screen and (min-width: 960px)"

  # Preon classes
  classes:
    - label: bg-
      css-property: background-color
      rule: 
        - color
    - label: fill-
      css-property: fill
      rule: 
        - color
    - label: ""
      css-property: color
      rule: 
        - color
    - label: ""
      css-property: position
      rule: 
        - position
    - label: h
      css-property: height
      rule:
        - scaled
        - percentaged
        - discrete
    - label: w
      css-property: width
      rule:
        - scaled
        - percentaged
        - discrete
    - label: maxw
      css-property: max-width
      rule:
        - special-sizes
        - percentaged
        - discrete
    - label: maxh
      css-property: max-height
      rule:
        - special-sizes
        - percentaged
        - discrete
    - label: minw
      css-property: min-width
      rule:
        - special-sizes
        - percentaged
        - discrete
    - label: minw
      css-property: min-height
      rule:
        - special-sizes
        - percentaged
        - discrete
    - label: before-w
      css-property: width
      function: preonize-before
      rule:
        - scaled
        - percentaged
        - discrete
    - label: before-h
      css-property: height
      function: preonize-before
      rule:
        - scaled
        - percentaged
        - discrete
    - label: after-w
      css-property: width
      function: preonize-after
      rule:
        - scaled
        - percentaged
        - discrete
    - label: after-h
      css-property: height
      function: after-before
      rule:
        - scaled
        - percentaged
        - discrete
    - label: t
      css-property: top
      rule:
        - scaled
        - negative-scaled
        - percentaged
        - discrete
    - label: b
      css-property: bottom
      rule:
        - scaled
        - negative-scaled
        - percentaged
        - discrete
    - label: l
      css-property: left
      rule:
        - scaled
        - negative-scaled
        - percentaged
        - discrete
    - label: r
      css-property: right
      rule:
        - scaled
        - negative-scaled
        - percentaged
        - discrete
    - label: pa
      css-property: padding
      rule: 
        - scaled
    - label: pl
      css-property: padding-left
      rule:
        - scaled
        - discrete
    - label: pr
      css-property: padding-right
      rule:
        - scaled
        - discrete
    - label: pt
      css-property: padding-top
      rule:
        - scaled
        - discrete
    - label: pb
      css-property: padding-bottom
      rule:
        - scaled
        - discrete
    - label: ma
      css-property: margin
      rule:
        - scaled
        - special-sizes
        - percentaged
        - discrete
    - label: ml
      css-property: margin-left
      rule:
        - scaled
        - special-sizes
        - percentaged
        - discrete
        - negative-scaled
    - label: mr
      css-property: margin-right
      rule:
        - scaled
        - special-sizes
        - percentaged
        - discrete
        - negative-scaled
    - label: mt
      css-property: margin-top
      rule:
        - scaled
        - special-sizes
        - percentaged
        - discrete
        - negative-scaled
    - label: mb
      css-property: margin-bottom
      rule:
        - scaled
        - special-sizes
        - percentaged
        - discrete
        - negative-scaled
    - label: boa
      css-property: border-radius
      rule:
        - limited-percentage
        - scaledsmall
    - label: bwa
      css-property: border-width
      rule:
        - tiny
    - label: bwl
      css-property: border-left-width
      rule:
        - tiny
    - label: bwb
      css-property: border-right-width
      rule:
        - tiny
    - label: bwt
      css-property: border-top-width
      rule:
        - tiny
    - label: bwb
      css-property: border-bottom-width
      rule:
        - tiny
    - label: bs-
      css-property: border-style
      rule:
        - border-style
    - label: bc-
      css-property: border-color
      rule:
        - color
    - label: t
      css-property: text-transform
      rule:
        - text
    - label: align
      css-property: text-align
      rule:
        - alignment
    - label: fw
      css-property: font-weight
      rule:
        - weight
    - label: td
      css-property: text-decoration
      rule:
        - decoration
    - label: ls
      css-property: letter-spacing
      rule:
        - letter-spacing
    - label: fs
      css-property: font-size
      rule:
        - font-size
    - label: lh
      css-property: line-height
      rule:
        - baselined
    - label: lst-
      css-property: list-style-type
      rule:
        - list-style
    - label: d
      css-property: display
      rule:
        - display
    - label: after-d
      css-property: display
      function: preonize-after
      rule:
        - display
    - label: bwb
      css-property: border-bottom-width
      rule:
        - tiny
    - label: shadow
      css-property: box-shadow
      rule:
        - shadow
    - label: ff-
      css-property: font-family
      rule:
        - font-family
    - label: hover-color-
      css-property: color
      function: preonize-hover
      rule:
        - color
    - label: hover-color-
      css-property: color
      rule:
        - color
    - label: bghover-color-
      css-property: background-color
      rule:
        - color
    - label: ""
      css-property: overflow
      rule:
        - overflow
    - label: "x-"
      css-property: overflow-x
      rule:
        - overflow
    - label: "y-"
      css-property: overflow-y
      rule:
        - overflow
    - label: "o"
      css-property: opacity
      rule:
        - decimal
    - label: "z-"
      css-property: z-index
      rule:
        - numbers
    - label: "ob-"
      css-property: object-fit
      rule:
        - image-fill
